### ISSUE TITLE
Laravel 5.4 support

### ISSUE THREAD

**Issue by denis-chmel** [Xethron/migrations-generator#117]
Aftr adding `Xethron\MigrationsGenerator\MigrationsGeneratorServiceProvider::class` into app.php and running php artisan I am getting:
````
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Illuminate\Foundation\Application::share()
````

**Comment by thatdoorsajar** [comment]
I am also getting this error after migrate to 5.4

**Comment by amravazzi** [comment]
Same here

**Comment by sineld** [comment]
+1

**Comment by sineld** [comment]
Did not work for Laravel 5.4 so I created an empty 5.3 project and successfully generated my migrations then copied them to the 5.4 project. Everything worked great. Thanks.

**Comment by yodahack** [comment]
You will find fix here so you can merge it if you like

https://github.com/yodahack/migrations-generator/releases/tag/v2.0.1

I am not sure if that is the way it should be organized but I am learning my ways here.

**Comment by Agapito78** [comment]
+1

**Comment by vitorn1234** [comment]
Don`t know if it helps but try 

https://github.com/UniSharp/laravel-filemanager/pull/187

Using singleton method instead share method. Share method is now deprecated.

**Comment by Xethron** [comment]
Fixed, closing issue

**Comment by Xethron** [comment]
Oh, and a big thanks to @Roboroads and @VRuzhentsov for fixing this!
