### ISSUE TITLE
migrate:generate fails with Way\Generators\Filesystem\FileNotFound error

### ISSUE THREAD

**Issue by sneakyimp** [Xethron/migrations-generator#122]
I'm trying to run this command:
```
php artisan migrate:generate
```
and it fails with this output:
```
$ php artisan migrate:generate
Using connection: mysql

Generating migrations for: group_product_assoc, groups, product_hierarchy_assoc, product_product_assoc, products, replist, sessionsOLD, stores, tree, users, zipcode_coordinates

 Do you want to log these migrations in the migrations table? [Y/n] :
 > n

Setting up Tables and Index Migrations

                                                                                         
  [Way\Generators\Filesystem\FileNotFound]                                               
  /var/www/my-project/vendor/way/generators/src/Way/Generators/templates/migration.txt  
    
```

I'm running this on a virtual machine running Ubuntu 16.04 with php 7.0.15. My laravel version is 5.4.

How can I fix this?

**Comment by jhonkrave** [comment]
I have this same problem :/

**Comment by sneakyimp** [comment]
@jhonkrave Perhaps you should provide the details of your system (operating system, php version, laravel version) so that the devs can have more info about where the problem occurs?

**Comment by jhonkrave** [comment]
OS: Linux - Fedora 24
PHP Release: php 5.6.30
DBMA: Postgres 9.5.5
Laravel Release: Laravel 5.4

**Comment by sneakyimp** [comment]
I posted this question on StackOverflow and got an answer on how to fix this issue temporarily: http://stackoverflow.com/questions/42451134/laravel-5-4-migrategenerate-fails-with-way-generators-filesystem-filenotfound-e/42451554#42451554

**Comment by matriphe** [comment]
solution from @sneakyimp worked like a charm!

**Comment by stevevg** [comment]
I used:
`composer require way/generators`, but may have added a useless package, if the above soluton works...

**Comment by Xethron** [comment]
This issue has been resolved, simply run `composer update` to get the latest version.

Apologies for the inconvenience.
