### ISSUE TITLE
Class files does not exist

### ISSUE THREAD

**Issue by TheRealJAG** [Xethron/migrations-generator#130]
After following the instructions I'm getting the following error when running php artisan with laravel 5.4

`[ReflectionException]       
  Class files does not exist  
`
If I remove the 2 lines from the providers array, everything works again.

**Comment by marcelopm** [comment]
:+1:

**Comment by marcelopm** [comment]
You can try using this ugly workaround in GeneratorsServiceProvider::registerConfig()
`
$this->app->singleton('files', function () {
    return new Filesystem;
});
`
But that should happening earlier on the stack somewhere.

**Comment by TheRealJAG** [comment]
I moved on in my project without a fix to the MG install . Closing issue.
