### ISSUE TITLE
compatibility with Lumen 5.4

### ISSUE THREAD

**Issue by Haafiz** [Xethron/migrations-generator#137]
I am not sure if it is not compatible with Lumen or not. I am using Lumen 5.4 and it is giving this error:
```Call to undefined method Laravel\Lumen\Application::configPath()```
Previously it was saying Config class not found. So I added Config class alias in bootstrap/app.php but now above mentioned error.

So just wondering, how can I know if this is even compatible with Lumen or not?

**Comment by kakoma** [comment]
It isn't. You'd need to add a number of Helper functions to get it to work. This gist gives a good idea of where to start:
https://gist.github.com/mabasic/21d13eab12462e596120

**Comment by nicolanicola** [comment]
@Haafiz did you get this to work with Lumen?  I cannot get the generate command to even show up when running `php artisan`

**Comment by Xethron** [comment]
Unfortunately, Lumen compatibility isn't something I've looked at. Best case would be to generate the migrations in Laravel, and copy them over to Lumen.

If there is a simple fix that doesn't overly complicate the existing code, I'll be happy to merge a PR for it.
