### ISSUE TITLE
Requires PHP 7.1 instead of 5.6?

### ISSUE THREAD

**Issue by paulintrognon** [Xethron/migrations-generator#140]
Hi,

I wanted to install this package, and the installation fails:

> - doctrine/dbal v2.6.2 requires php ^7.1 -> your PHP version (7.0.19) does not satisfy that requirement.
> - xethron/migrations-generator v2.0.1 requires doctrine/dbal ~2.4 -> satisfiable by doctrine/dbal[v2.6.2].
> - Installation request for xethron/migrations-generator v2.0.1 -> satisfiable by xethron/migrations-generator[v2.0.1].

It appears that **migrations-generator** requires **doctrine/dbal v2.6.2** which requires **php ^7.1**. This is not really an issue but must be specified in your **composer.json**, [which says php>=5.4](https://github.com/Xethron/migrations-generator/blob/master/composer.json#L13)

**Comment by devonblzx** [comment]
Must be one of your other dependencies in your project.  I just installed this on PHP 7.0 and it works fine.  The composer.json only requires dbal 2.4

**Comment by Xethron** [comment]
Thanks @devonblzx for helping, your comment is much appreciated.

@paulintrognon: Yes, I don't believe there is a requirement for PHP7. The requirement seems to be from doctrine/dbal. It might be conflicting dependancies.

If you can find a way around it, or find out what dependency it conflicts with, I'd be more than happy to merge a PR. Feel free to re-open this anytime!

**Comment by paulintrognon** [comment]
Oh yes, I could not see that the `doctrine/dbal` version I had was not the same as the one of your package.

Thank you for your time!
