### ISSUE TITLE
 Xethron\MigrationsGenerator\MigrateGenerateCommand::handle() does not exist

### ISSUE THREAD

**Issue by sirolad** [Xethron/migrations-generator#141]
I keep getting this error when I try to use the package on L5.5. But I have a fix for it already

**Comment by justinharris198** [comment]
What is the fix?

**Comment by sirolad** [comment]
I changed the fire() method in the Generator class to handle(). I have a PR for it already.

**Comment by justinharris198** [comment]
Thank you!

**Comment by Xethron** [comment]
Thanks to @sirolad, @devLopez and @akalongman for their PR's. This has been merged in #145

**Comment by spfroc** [comment]
@sirolad It works~

**Comment by HermesGonzalez** [comment]
Thanks
