### ISSUE TITLE
Compatibility to Laravel 5.5

### ISSUE THREAD

**Issue by bandeh** [Xethron/migrations-generator#146]
Hi

I just wonder if migrations generator has any known compatibility issues with Laravel 5.5?

Best

**Comment by AbdurRehman26** [comment]
It has. when i run php arisan migrate:generate it says it doesnt have this command in the lists.. php artisan also doesnt have this command idk why

**Comment by denniskrol** [comment]
The fire() function in MigrateGenerateCommand needs to be renamed to handle(), then it works for me on 5.5

**Comment by Xethron** [comment]
This has been fixed in version 2.0.2, let me know if you still have any issues using this version

**Comment by denniskrol** [comment]
Edit: ignore me, I am a retard. I did  `php artisan generate:migration` instead of `php artisan migrate:generate`
