### ISSUE TITLE
Don't install laravel 5.5.14

### ISSUE THREAD

**Issue by viandanteoscuro** [Xethron/migrations-generator#149]
Hi, the composer fails:

C:\xampp\htdocs\api\cruscotto>composer require --dev "xethron/migrations-generator:~1.3.0"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for xethron/migrations-generator ~1.3.0 -> satisfiable by xethron/migrations-generator[v1.3.0].
    - Conclusion: remove laravel/framework v5.5.14
    - Conclusion: don't install laravel/framework v5.5.14
    - xethron/migrations-generator v1.3.0 requires illuminate/support ~4.1 -> satisfiable by illuminate/support[v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.13, v4.1.14, v4.1.15, v4.1.16, v4.1.17, v4.1.18, v4.1.19, v4.1.2, v4.1.20, v4.1.21, v4.1.22, v4.1.23,
 v4.1.24, v4.1.25, v4.1.26, v4.1.27, v4.1.28, v4.1.29, v4.1.3, v4.1.30, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - don't install illuminate/support v4.1.0|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.1|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.10|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.11|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.12|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.13|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.14|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.15|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.16|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.17|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.18|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.19|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.2|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.20|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.21|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.22|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.23|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.24|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.25|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.26|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.27|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.28|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.29|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.3|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.30|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.4|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.5|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.6|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.7|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.8|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.1.9|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.2.1|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.2.12|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.2.16|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.2.17|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.2.2|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.2.3|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.2.4|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.2.5|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.2.6|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.2.7|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.2.8|don't install laravel/framework v5.5.14
    - don't install illuminate/support v4.2.9|don't install laravel/framework v5.5.14
    - Installation request for laravel/framework (locked at v5.5.14, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.14].

How cai i fix this?

Thanks

**Comment by Xethron** [comment]
Hello.

Version 1 isn't compatible with Laravel 5. When adding new dependencies with composer, it is recommended that you leave out the version number so that you can get the latest version available.

Try running: `composer require --dev "xethron/migrations-generator"`
