### ISSUE TITLE
Installation via composer require --dev "xethron/migrations-generator" failing

### ISSUE THREAD

**Issue by djunehor** [Xethron/migrations-generator#195]
I think it has to do with the minimum requirement. I'm using Laravel 6.0
Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by wallacemyem** [comment]
`composer require oscarafdev/migrations-generator` this package is maintained
