### ISSUE TITLE
ForeignKeys migrations: drop issue

### ISSUE THREAD

**Issue by dpgover** [Xethron/migrations-generator#27]
When generating the dropForeign, laravel asks for the index name. The package is using the field name.

Having this up():

Schema::table('A', function(Blueprint $table)
        {
            $table->foreign('B_id', 'A_B_id_fkey')->references('id')->on('B')->onUpdate('RESTRICT')->onDelete('RESTRICT');
        });

Generates this down:

Schema::table('A', function(Blueprint $table)
        {
            $table->dropForeign('B_id');
        });

Should generate:

Schema::table('A', function(Blueprint $table)
        {
            $table->dropForeign('A_B_id_fkey');
        });

**Comment by Xethron** [comment]
Hello. Thank you for reporting this. This has been fixed in v1.3.0, let me know if you still experience any issues. :)
