### ISSUE TITLE
Column name with reserved character generates incorrect migration

### ISSUE THREAD

**Issue by bishopb** [Xethron/migrations-generator#30]
Supposing you have this:
```
mysql> create table test (`foo.bar` int);
Query OK, 0 rows affected (0.05 sec)

mysql> describe test;
+---------+---------+------+-----+---------+-------+
| Field   | Type    | Null | Key | Default | Extra |
+---------+---------+------+-----+---------+-------+
| foo.bar | int(11) | YES  |     | NULL    |       |
+---------+---------+------+-----+---------+-------+
1 row in set (0.00 sec)
```

Then the generated migration `$table->integer('foo.bar')->nullable();` is incorrect: Eloquent explodes that to a table name and column, that is this incorrect SQL: 
```
create table test (`foo`.`bar` int);  /* oops, no table `foo` */
```
The proper generation should be:
```
$table->integer(DB::raw('`foo.bar`')->nullable();
```
where both the list of reserved characters and the escape character is driver-specific.  The patch for this seems straightforward: if the column name contains a driver-specific reserved character, wrap the generation in a `DB::raw` using the driver-specific escape character.  Possibly an even simpler solution is to wrap *ALL* column names in `DB::raw`...

*P.S.: I'm not saying a column like this is a good idea! I did just encounter it, though, reversing a legacy system.*

**Comment by Xethron** [comment]
Closing this as "wont-fix", if you want to fix it, you are welcome to do so.
