### ISSUE TITLE
boolean field is not migrated properly

### ISSUE THREAD

**Issue by rebin** [Xethron/migrations-generator#31]
I have a table with boolean field with default value set as false. When I run migration it shows 
            $table->boolean('deleted')->default('');
default is shown as null field. Can you please check and let me know a solution for same

**Comment by jpcaparas** [comment]
Same issue I have with a postgres db

**Comment by Xethron** [comment]
Seems to be related to #79 and #83

**Comment by Xethron** [comment]
Fixed :)
