### ISSUE TITLE
Support Laravel 5

### ISSUE THREAD

**Issue by ssx** [Xethron/migrations-generator#33]
Can you bump the version up to support Laravel 5 too.

**Comment by GC-Mark** [comment]
Any updates on this?

**Comment by ivomarino** [comment]
I would also be interested in this, actually during composer update I get:

```ruby
% composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for xethron/migrations-generator dev-master -> satisfiable by xethron/migrations-generator[dev-master].
    - Conclusion: remove laravel/framework v5.0.0
    - xethron/migrations-generator dev-master requires illuminate/support ~4.1 -> satisfiable by illuminate/support[v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.13, v4.1.14, v4.1.15, v4.1.16, v4.1.17, v4.1.18, v4.1.19, v4.1.2, v4.1.20, v4.1.21, v4.1.22, v4.1.23, v4.1.24, v4.1.25, v4.1.26, v4.1.27, v4.1.28, v4.1.29, v4.1.3, v4.1.30, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.1, v4.2.12, v4.2.16, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - don't install illuminate/support v4.1.0|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.1|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.10|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.11|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.12|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.13|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.14|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.15|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.16|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.17|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.18|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.19|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.2|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.20|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.21|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.22|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.23|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.24|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.25|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.26|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.27|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.28|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.29|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.3|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.30|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.4|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.5|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.6|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.7|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.8|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.9|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.1|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.12|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.16|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.2|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.3|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.4|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.5|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.6|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.7|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.8|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.9|don't install laravel/framework v5.0.0
    - Installation request for laravel/framework 5.0.* -> satisfiable by laravel/framework[v5.0.0].
```

**Comment by jamisonvalenta** [comment]
I decided to start the slow process of moving one of my CI apps over to L5 now that 5.0 is out.  First feature will be migrations.  I fuddled with it a bit last night and got it to run.  Some code changes, but mostly just different setup config (where you register artisan commands,  binding the migration repository interface, etc).  L5 pushed a lot of package=>framework binding points around.  Config is totally different.

Also, there's an issue with `way\generators` and binding its shipped config (just like with all L4 packages).  I'll need to check to see if he has a `~2` compatible update for L5 or if we'll have to deal with upgrading to `~3`.

Hopefully I'll have a PR up of some sort in the next couple of days.

**Comment by JayBizzle** [comment]
@jamisonvalenta goos stuff, looking forward to the PR

**Comment by Xethron** [comment]
@jamisonvalenta I also started playing with it last weekend, and it appears we would have to rewrite the code I stole from @JeffreyWay as he won't be updating his Generators.

We have one of three options mostly. Submit a PR to the @laravel source for the features required to write the migrations, extend their class and build in our own functionality, or don't depend on other classes and let the plugin handle everything.

Personally, I'd push for the first option. It means there's less code to maintain, and if the styling ever changes, its the responsibility of Laravel to update it.

Doctrine and the plugin itself seems to work fine with some minor changes.

I have created a new branch called l5 that we can all work on. The composer package has also been updated to work with Laravel 5, so you can require it in composer as such: 
```
"require-dev": {
    "xethron/migrations-generator": "dev-l5"
}
```

I'm also thinking that the actual structure of the classes might need to be revised... I never really liked it. Any ideas are welcome.

@jamisonvalenta would like to see what you're busy with so we don't do double work. I'm going to spend some time extending the L5 migrations generator class, and work in the features we require to write specific values. Once done, I'll see if I can get it into the Laravel source which would help other packages that might want to do something similar.

**Comment by jamisonvalenta** [comment]
Ugh.  Sorry, composer is being a serious pain.  

This package almost works out of the box.  There a couple of changes necessary inside of the migrations service provider, and there are also a few changes that need to be made to `way/generators` to be L5 ready.  My thought has always been to do a two-fold approach:
 1 - spin up a temporary package that allows the package to be used with L5
 2 - consider a rewrite
 3 - do the rewrite

If I could just get composer to behave I would be happy to host the changes to way/generators that would get this package up and running again while @Xethron contemplates/implements a rewrite.  

Ok.  Diving in again.

**Comment by jamisonvalenta** [comment]
Composer debugged.  @Xethron, I have a PR up: https://github.com/Xethron/migrations-generator/pull/40.  Pull failed unit testing, but it looks like at least one of the tests will need to be rewritten (`registers_the_package`), since that doesn't matter in L5 anymore.

**Comment by Xethron** [comment]
Everything seems to be working. Closing issue

**Comment by ssx** [comment]
Cheers ears! :+1:
