### ISSUE TITLE
JSON datatype not handled for PostgreSQL

### ISSUE THREAD

**Issue by frankpinto** [Xethron/migrations-generator#35]
I'm using PostgreSQL and I have two tables with a JSON datatype. When generating migrations it throws the error "Unknown database type json requested, Doctrine\DBAL\Platforms\PostgresqlPlatform may not support it".

I fixed it by adding:

```php
$connection->getDatabasePlatform()->registerDoctrineTypeMapping('json', 'string');
```

to \Xethron\MigrationsGenerator\Generators\SchemaGenerator in the constructor

**Comment by Xethron** [comment]
Hello @frankpinto. Thanks for reporting this. I believe this was added in #76, let me know if this is still an issue.
