### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by itsazzad** [Xethron/migrations-generator#38]
Problem 1
    - Installation request for xethron/migrations-generator dev-master -> satisfiable by xethron/migrations-generator[dev-master].
    - xethron/migrations-generator dev-master requires way/generators 2.* -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

In my composer file: 
	"require-dev": {
		"way/generators": "~3.0",
	    "xethron/migrations-generator": "dev-master"
	}

**Comment by bryceadams** [comment]
Confirmed

**Comment by Xethron** [comment]
My apologies, I forgot to add this in the readme.

You'll have to add this to your composer.json:

```
"repositories": [
    {
        "type": "git",
        "url": "git@github.com:jamisonvalenta/Laravel-4-Generators.git"
    }
]
```

Let me know if you still have any issues.

**Comment by youyi1314** [comment]
It need username and password for this?

Loading composer repositories with package information
Cloning failed using an ssh key for authentication, enter your GitHub credential
s to access private repos
A token will be created and stored in ".../Compos
er/auth.json", your password will never be stored
To revoke access to this token you can visit https://github.com/settings/applica
tions
Username:

**Comment by JeremyMulvihill** [comment]
I am still having this problem. 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for xethron/migrations-generator dev-master -> satisfiable by xethron/migrations-generator[dev-master].
    - xethron/migrations-generator dev-master requires way/generators 2.* -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

**Comment by JeremyMulvihill** [comment]
My composer file:

    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1",
        "xethron/migrations-generator": "dev-l5",
        "way/generators": "dev-feature/laravel-five-stable",
        "way/generators": "~3.0",
        "xethron/migrations-generator": "dev-master",
        "way/generators": "dev-master"
    },

    "repositories": [
        {
            "type": "git",
            "url": "git@github.com:jamisonvalenta/Laravel-4-Generators.git"
        }
    ],

**Comment by itsazzad** [comment]
@JeremyMulvihill What is your Laravel version?

**Comment by JeremyMulvihill** [comment]
My Laravel version is 5.1

**Comment by itsazzad** [comment]
@JeremyMulvihill  try with 
`    "way/generators": "~2.0",`
