### ISSUE TITLE
laravel 5 not install

### ISSUE THREAD

**Issue by uradvd85** [Xethron/migrations-generator#41]
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for xethron/migrations-generator dev-l5 -> satisfiable by xethron/migrations-generator[dev-l5].
    - xethron/migrations-generator dev-l5 requires way/generators dev-feature/laravel-five-stable -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by MarcGuay** [comment]
Just encountered the same problem.  Problem seems to be here https://github.com/Xethron/migrations-generator/commit/2bc1e1f0a0d732aecc97d5fac552dd2da59201ab#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780.  Is branch is actually called "feature/laravel-five-stable"? (https://github.com/jamisonvalenta/Laravel-4-Generators/tree/feature/laravel-five-stable)

**Comment by jamisonvalenta** [comment]
Hey all - 

I've submitted a PR to explain how to avoid this issue:  https://github.com/Xethron/migrations-generator/pull/42.  There is a composer bug that requires us to declare all non-packagist-declared repos in the root `composer.json`.

**Comment by MarcGuay** [comment]
Hi and thanks.  I tried the proposed solution and am receiving the same error message.  Here is the relevant parts of composer.json in case I've misunderstood something:

```
        "require-dev": {
                "xethron/migrations-generator": "dev-l5"
        },
        "repositories": [
                {
                        "type": "git",
                        "url": "git@github.com:jamisonvalenta/Laravel-4-Generators.git"
                }
        ],
```

**Comment by jamisonvalenta** [comment]
Hmmm. Composer is such an odd duck sometimes. 

I can recreate this issue by dropping the repositories key in my project `composer.json`.  The issue then resolves when I add it back in (after deleting my entire vendor directory and `composer.lock`).  Perhaps you need to update your composer install with `composer self-update`?

**Comment by MarcGuay** [comment]
I self-updated composer, removed /vendor and .lock, updated, and got the same problem.  I removed the required-dev entry and left the repositories one, composer updated fine, then re-added the required-dev entry and got the same error.  Thanks for your efforts.

`Composer version 1.0-dev (833ce984264204e7d6576ab082660105c7d8f04c) 2015-02-17 21:55:441`

**Comment by alcohol** [comment]
> There is a composer bug that requires us to declare all non-packagist-declared repos in the root composer.json.

Wrong, this is [documented](https://getcomposer.org/doc/04-schema.md#repositories) (note the **root-only** indication).

**Comment by MarcGuay** [comment]
Problem can be solved by adding both `"way/generators": "dev-feature/laravel-five-stable"` to `require-dev` and the `repositories` section above.

**Comment by geocine** [comment]
@MarcGuay  thanks, I got it working. I used your solution.

**Comment by joannahalpern** [comment]
Hi, I'm a beginner using laravel 5 and am having the same problem as @uradvd85 but I'm quite confused by the solution that you proposed @jamisonvalenta and @MarcGuay. Would someone mind explaining to me step by step how I can install migrations-generator? 

Thanks in advance! I really appreciate the help!

**Comment by jamisonvalenta** [comment]
@joannahalpern 

Sometimes the snippets from `composer.json` that we include are hard to figure out how to apply.  Here's a full working composer.json file from a test Laravel `5.0` project.  Note the contents of the `require-dev` and `repositories` keys.

```json
{
    "name": "jamisonvalenta/myproject",
    "description": "Description",
    "keywords": [],
    "license": "MIT",
    "type": "project",
    "require": {
        "laravel/framework": "5.0.*"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1",
        "xethron/migrations-generator": "dev-l5",
        "way/generators": "dev-feature/laravel-five-stable"
    },
    "repositories": [
        {
            "type": "git",
            "url": "git@github.com:jamisonvalenta/Laravel-4-Generators.git"
        }
    ],
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "post-create-project-cmd": [
            "php -r \"copy('.env.example', '.env');\"",
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "source"
    },
    "minimum-stability": "stable"
}
```

**Comment by joannahalpern** [comment]
@jamisonvalenta Thank you for your help and quick response!

I am still getting errors so hopefully if I tell you what I have done you can help me.
I updated my composer.json file as you showed above. I forked Laravel-4-Generators and in the for repositories I have it pointing at my forked repository as so:
```    
"repositories": [
        {
            "type": "git",
            "url": "https://github.com/joannahalpern/Laravel-4-Generators"
        }
    ],
```
Now, when I do composer update I get the following error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package way/generators could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Installation request for xethron/migrations-generator dev-l5 -> satisfiable by xethron/migrations-generator[dev-l5].
    - xethron/migrations-generator dev-l5 requires way/generators dev-feature/laravel-five-stable -> no matching package found.
```

Do you know how I can fix this? Thanks again for your help!

**Comment by jamisonvalenta** [comment]
Did you fork Laravel-4-Generators from https://github.com/jamisonvalenta/Laravel-4-Generators or https://github.com/JeffreyWay/Laravel-4-Generators? 

It looks like you forked Way's repo instead of mine, which is why the branch isn't resolving - Way's doesn't have the `feature/laravel-five-stable` branch.  If you fork mine you'll get the branch and it should resolve correctly.

**Comment by joannahalpern** [comment]
Very good catch! It worked! Thank you so much for you help and figuring out what mistake I made! Have a great night!

**Comment by raksrivastava** [comment]
Hi, I am using Laravel 5. But this is not working for me. I am getting following error.
[RuntimeException] Failed to clone https://230f1de20f16d31398bbbf36155c6e0be57ecf65:***@github .com/jamisonvalenta/Laravel-4-Generators.git, git was not found, check that it is installed and in your PATH env. 'git' is not recognized as an internal or external command, operable program or batch file.
update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no- progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [p ackagesN]

**Comment by alcohol** [comment]
@raksrivastava Maybe you should try reading the error message.

**Comment by raksrivastava** [comment]
Thanks, Now it is working.

**Comment by llbbl** [comment]
are the service providers the same for L5/?

**Comment by santoshachari** [comment]
Hey @joannahalpern 

I am trying to use the package but it keeps throwing me this error:

```
  [RuntimeException]
  Failed to clone https://2604b128a28e206d476380b6e1b9e7da39de1bf7:***@github
  .com/jamisonvalenta/Laravel-4-Generators.git, git was not found, check that
   it is installed and in your PATH env.
  'git' is not recognized as an internal or external command,
  operable program or batch file.



update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock]
 [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-
progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader]
 [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [p
ackagesN]
```

Here's my composer.json (I am on Laravel 5)
```
{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
	"require": {
		"laravel/framework": "5.0.*"
	},
	"require-dev": {
		"phpunit/phpunit": "~4.0",
		"phpspec/phpspec": "~2.1",
		 "xethron/migrations-generator": "dev-l5",
        "way/generators": "dev-feature/laravel-five-stable"
	},
	"repositories": [
        {
            "type": "git",
            "url": "git@github.com:jamisonvalenta/Laravel-4-Generators.git"
        }
    ],
	"autoload": {
		"classmap": [
			"database"
		],
		"psr-4": {
			"App\\": "app/"
		}
	},
	"autoload-dev": {
		"classmap": [
			"tests/TestCase.php"
		]
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php -r \"copy('.env.example', '.env');\"",
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	}
}
```

**Comment by Xethron** [comment]
Closing issue. Let me know if there are any other problems.
