### ISSUE TITLE
Does not make "generate" functions compatible with L5

### ISSUE THREAD

**Issue by MarcGuay** [Xethron/migrations-generator#43]
Although this adds the "generate" functions to artisan, they do not work with Laravel 5, only `migrate:generate` has been made to work with L5.  Perhaps a note stating this in the readme would be useful.

Updated: It seems as though some of the generate functions do work as expected, `resource` for example.  `scaffold` does not however.

**Comment by jamisonvalenta** [comment]
I was hoping that `way/generators` would work mostly out of the box.  However, support for L5 was discontinued a while ago.  If you fix stuff, feel free to submit a PR to the repo we are currently referencing: https://github.com/jamisonvalenta/Laravel-4-Generators.  Additionally, if you find a `way/generators` fork that is more updated than the basic work I did, we can adjust the repo pointer in the docs.
