### ISSUE TITLE
Hey, since way/generator has supported L5, do i still need to installed the forked one since I have already installed the original way/generator for laravel 5?

### ISSUE THREAD

**Issue by woodytang** [Xethron/migrations-generator#50]
Hey, since way/generator has supported L5, do i still need to installed the forked one since I have already installed the original way/generator for laravel 5?

**Comment by Xethron** [comment]
Haven't tried it with the new one, you are most welcome to give it a shot and tell us how it went. If it doesn't work, would highly appreciate a PR :)
