### ISSUE TITLE
Issue with octobercms

### ISSUE THREAD

**Issue by JurekRaben** [Xethron/migrations-generator#53]
I added some custom tables to my octobercms database and would like to generate a model from these tables, using this generator + https://packagist.org/packages/user11001/eloquent-model-generator

Now if I fire "php artisan migrate:generate" or even "php artisan help", the following error will appear:

[ErrorException]                                                                                                                               
  Argument 5 passed to Xethron\MigrationsGenerator\MigrateGenerateCommand::__construct() must be an instance of Illuminate\Config\Repository, i  
  nstance of October\Rain\Config\Repository given, called in vendor/xethron/migrations-generator/src/Xethron/MigrationsGe  
  nerator/MigrationsGeneratorServiceProvider.php on line 30 and defined                               

Any idea how to fix this? Is it possible to use this within a OctoberCMS installation or have a setup another laravel environment for this migration first, and then put it manually it octobercms?

thx for help.

**Comment by Xethron** [comment]
Hello @JurekRaben. Sorry for not responding earlier. Did you manage to solve your problem?

**Comment by JurekRaben** [comment]
Sorry, don't remember :) Will try to check.

**Comment by Xethron** [comment]
No worries dude, I should've replied a lot earlier! Closing the issue for now. You are welcome to reopen it if you need to. :)
