### ISSUE TITLE
Laravel 5.1

### ISSUE THREAD

**Issue by dagonar** [Xethron/migrations-generator#56]
Is the installation procedure for the generator the same as Laravel 5? Or do the tools need to be updated to this version. I get a "Class 'Way\Generators\GeneratorServiceProvider' not found" exception when trying to run artisan.

**Comment by michaelachrisco** [comment]
I am reporting the same issue. Looks like the application is not pulling the correct classes in the config/app.php

**Comment by michaelachrisco** [comment]
Ok solved the problem. Add 
```php
        'Way\Generators\GeneratorsServiceProvider',
        'Xethron\MigrationsGenerator\MigrationsGeneratorServiceProvider'
```
at the end of the providers block in config/app

The Way repo expects Illuminate\Support\ServiceProvider; but its not declared until later.

**Comment by DeeJaVu** [comment]
@michaelachrisco for laravel 5.1 the correct way to add the providers is like this

    Way\Generators\GeneratorsServiceProvider:class,
    Xethron\MigrationsGenerator\MigrationsGeneratorServiceProvider::class,

**Comment by pixelspy** [comment]
I have the classes in config/app but i still get an error. any idea why?
