### ISSUE TITLE
Class 'Xethron\MigrationsGenerator\MigrationsGeneratorServiceProvider' not found

### ISSUE THREAD

**Issue by Akhanto** [Xethron/migrations-generator#58]
Hi, 
I want to use the migrations-generator. Trying the "php artisan" command I get the above error. 

Here are my directories, the serviceproviders and the error: 
https://gyazo.com/df1642a3b2dbc8c51337de4d71917d89 

I'm using Laravel 5, PHP 5.6

Could you please help?

**Comment by vjandrea** [comment]
If you run `composer dump-autoload` does the error persist?

**Comment by Akhanto** [comment]
unfortunately yes

**Comment by Akhanto** [comment]
I made a mistake and had to reinstall.
