### ISSUE TITLE
Couldn't able to fetch comments for a column 

### ISSUE THREAD

**Issue by rajangupta24** [Xethron/migrations-generator#59]
I am using L5.1 and it worked fine for me and I am thankful about that.

But ubable to fetch comments from tables so I added them manually.

**Comment by Xethron** [comment]
Hello,

There are two open PR's that aim to fix this, #61 and #52. If you can please test it and let me know if it works.

**Comment by Xethron** [comment]
This has now been added to 1.3.0. Let me know if you are still having problems :)
