### ISSUE TITLE
Xethron/migrations-generator could not be found

### ISSUE THREAD

**Issue by Troyd-Destin** [Xethron/migrations-generator#68]
"require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8.*|3.0.*",
        "symfony/dom-crawler": "2.8.*|3.0.*",
        "xethron/migrations-generator": "dev-15",
        "way/generators": "dev-feature/laravel-five-stable"
    },

  "repositories": {
        "repo-name": {
            "type": "git",
            "url": "git@github.com:jamisonvalenta/Laravel-4-generators.git"
        }
    }

in my composer.json, I receive the error  

"Xethron/migrations-generator could not be found or there is a  typo"

I have followed the instructions to the letter on the library home page.

**Comment by disperun** [comment]
It seems that you have a typo inside the package definition.
You are using "dev-**1**5" (in words ONE) but it should be L ("dev-**l**5").

Try this:
"xethron/migrations-generator": "dev-l5",

**Comment by Xethron** [comment]
Thanks @disperun :) Closing issue
