### ISSUE TITLE
Failed to clone git@github.com:jamisonvalenta/Laravel-4-generators.git, git was not found

### ISSUE THREAD

**Issue by jymden** [Xethron/migrations-generator#70]
I'm getting this error. I should have no typos. Everything is copied directly from the readme.

[RuntimeException]
  Failed to clone git@github.com:jamisonvalenta/Laravel-4-generators.git, git was not found, check that it is installed and in your PATH env.
  'git' is not recognized as an internal or external command,
  operable program or batch file.

 "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8.*|3.0.*",
        "symfony/dom-crawler": "2.8.*|3.0.*",
        "xethron/migrations-generator": "dev-l5",
        "way/generators": "dev-feature/laravel-five-stable" },

"repositories": {
        "repo-name": {
            "type": "git",
            "url": "git@github.com:jamisonvalenta/Laravel-4-generators.git"
        }

**Comment by malikwaqas09** [comment]
same here

**Comment by s0nink1** [comment]
any solution ? same problem

**Comment by Xethron** [comment]
The new version does not make use of jamisonvalenta/Laravel-4-generators.git. So you can remove the repository from your composer.json, as well as removing way/generators. And change `xethron/migrations-generator` to use version "~2.0.1"

**Comment by Cesar9611** [comment]
Hello unfortunately I have the same error could you tell me how to fix it
