### ISSUE TITLE
Undefined index: index_type

### ISSUE THREAD

**Issue by mehmetkirkoca** [Xethron/migrations-generator#72]
I got "Undefined index: index_type" error. I followed these steps. I dont know why I got this error. 

root@user-System-Product-Name:/var/www/x# php artisan migrate:generate
Using connection: mysql

Generating migrations for: x, y, z, Etc

 Do you want to log these migrations in the migrations table? [Y/n] :

> Y

 Next Batch Number is: 1. We recommend using Batch Number 0 so that it becomes the "first" migration [Default: 0] :

> 0
> Setting up Tables and Index Migrations

  [ErrorException]  
  Undefined index: index_type

**Comment by Xethron** [comment]
Is this still an issue? Can you give me the file and line number this happened? Closing for now, feel free to reopen it :)
