### ISSUE TITLE
Package not found [solved]

### ISSUE THREAD

**Issue by maantje** [Xethron/migrations-generator#73]
The requested package way/generators dev-feature/laravel-five-stable exists as way/generators[1.0, 1.1, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.6.1, 3, 3.0.1, 3.0.2, 3.0.3, dev-master, dev-rewrite] but these are rejected by your constraint.

Pulling in way/generators:dev-master does work but then the migrations-generator fails with

" - Installation request for xethron/migrations-generator dev-l5 -> satisfiable by xethron/migrations-generator[dev-l5].
    - xethron/migrations-generator dev-l5 requires way/generators dev-feature/laravel-five-stable -> no matching package found"

**Comment by alvinbakker** [comment]
This issue is not solved as I get the same error

**Comment by alvinbakker** [comment]
Oh wait... The description on how to install is incorrect. The last line should be:
composer config repositories.repo-name git "https://github.com/jamisonvalenta/Laravel-4-Generators.git"

**Comment by Xethron** [comment]
This seems to be related to #82 who requires git to install it. Will try updating the url to the https version.

Also, #80 suggests replacing git with vcs to fix another bug
