### ISSUE TITLE
php artisan migrate:generate json type was unsupported.

### ISSUE THREAD

**Issue by lance-dd** [Xethron/migrations-generator#74]
php artisan migrate:generate

[Doctrine\DBAL\DBALException]
Unknown database type json requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.

Didn`t support type json ,my database is mysql version >=5.7 .

![](https://cloud.githubusercontent.com/assets/1124879/14907119/edb3278c-0df6-11e6-8990-bc27c3ffd211.png)

**Comment by Xethron** [comment]
Hello @lance-dd. Thanks for reporting this. I believe this was added in #76, let me know if this is still an issue.
