### ISSUE TITLE
local.ERROR: exception 'ReflectionException' with unrelated package after composer update

### ISSUE THREAD

**Issue by OdinsHat** [Xethron/migrations-generator#77]
After installing using the Laravel 5 installation instructions to install the generators on Laravel 5.2 I get the following problem.

When I run `php artisan` to check the list of commands I get the following error:

```
local.ERROR: exception 'ReflectionException' with message 'Class files does not exist' in /var/www/[...]/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
```

Apparently this is a common problem when there's an issue with the config. 

When I comment out the two Providers lines for this plugin `php artisan` starts working again.

```
        //Way\Generators\GeneratorsServiceProvider::class,
        //Xethron\MigrationsGenerator\MigrationsGeneratorServiceProvider::class,
```

**Comment by Xethron** [comment]
Hello @OdinsHat, did you manage to fix your problem?
