### ISSUE TITLE
/dev/null/vcs does not exist and could not be created.

### ISSUE THREAD

**Issue by lijinma** [Xethron/migrations-generator#80]
Using commands as follow will fix the issue:

    composer config repositories.repo-name vcs "git@github.com:jamisonvalenta/Laravel-4-Generators.git"

The type is `vcs` but not `git`

**Comment by Xethron** [comment]
Hello @lijinma, will have to test it out. Thanks for reporting this!

**Comment by Xethron** [comment]
Confirmed. Closing this one as a duplicate of #73
