### ISSUE TITLE
while updating : composer update

### ISSUE THREAD

**Issue by malikwaqas09** [Xethron/migrations-generator#82]
[RuntimeException]
  Failed to clone git@github.com:jamisonvalenta/larave-4-generators.git, git was not found, check that it is installed and in you
  r PATH env.
  'git' is not recognized as an internal or external command,
  operable program or batch file.

**Comment by Xethron** [comment]
Hello @malikwaqas09, I assume that Composer is trying to pull down the source using git. You might have to install git for Composer to work. This question however is more related to Composer, I'm not 100% sure of its internal workings, but I assume installing git will fix your issue.

**Comment by Xethron** [comment]
@malikwaqas09 actually, according to #73, replacing the line in the instructions with this one, might fix your problem:
`composer config repositories.repo-name git "https://github.com/jamisonvalenta/Laravel-4-Generators.git"`

**Comment by malikwaqas09** [comment]
Thanks Xethron i appreciate your help and time, i just removed that line from composer and updated it worked.

**Comment by Xethron** [comment]
Awesome, sorry for the late reply. Glad it helped.
