### ISSUE TITLE
Generated migrations don't follow PSR-1 and PSR-2  coding standards

### ISSUE THREAD

**Issue by ifduyue** [Xethron/migrations-generator#86]
http://www.php-fig.org/psr/psr-1/
http://www.php-fig.org/psr/psr-2/

Let me know if you prefer a pull-request

**Comment by Xethron** [comment]
This is actually not easy, as I was using Jeffery Way's generator package to generate these.

This package is due for a rewrite, to remove those dependencies, and allow for more flexibility... So will definitely have it follow PSR2 once done.
