### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by KKSzymanowski** [Xethron/migrations-generator#90]
There is a typo at [this](https://github.com/Xethron/migrations-generator/blob/master/src/Xethron/MigrationsGenerator/MigrateGenerateCommand.php#L183) line.

Should be `either` instead of `ether`.
Same goes for L5 branch.

**Comment by Xethron** [comment]
Awesome! Thanks for spotting that.

**Comment by KKSzymanowski** [comment]
I'm good at opening annoying issues.

**Comment by Xethron** [comment]
Well, its an easy fix, why not do it yourself and get a Hacktoberfest t-shirt? Then you did an easy PR :)

**Comment by KKSzymanowski** [comment]
There you go: https://github.com/Xethron/migrations-generator/pull/93

**Comment by Xethron** [comment]
Merged
