### ISSUE TITLE
connection() is not added when using --connection

### ISSUE THREAD

**Issue by skys215** [Xethron/migrations-generator#92]
Hi,

I found that the `connection()` is not added when using `--connection=` argument.
How about adding it when generating migration?

Regards,

**Comment by Xethron** [comment]
Ah, you mean in the generated output? Thats a great idea!

**Comment by Xethron** [comment]
Fixed in #95. Please test and let me know if it works :)

**Comment by Xethron** [comment]
Merged, closing issue
