### ISSUE TITLE
Sqlite requires unique index name database-wide

### ISSUE THREAD

**Issue by chrispecoraro** [Xethron/migrations-generator#94]
Sqlite requires that the index name is unique database-wide. We could add a flag to prepend the table name for the sake of uniqueness to each id when converting from say, MySQL to Sqlite (for migrations and seeding used in testing).

**Comment by Xethron** [comment]
This is already done by Laravel when using default names. The idea behind the migration generator is to duplicate the current database as much as possible in the generators.
Perhaps we should add a field that allows you to generate the migrations without a index name? This will allow Laravel to choose the name instead. Not sure if this is something you'd like to create a PR for?
For the time being, you can just delete the names off of all your indexes and it should work. :)

**Comment by Xethron** [comment]
I see this is already a feature: use --defaultIndexNames and --defaultFKNames
Closing issue
