### ISSUE TITLE
support json type?

### ISSUE THREAD

**Issue by csi0n** [Xethron/migrations-generator#99]
i get this exception,
[Doctrine\DBAL\DBALException]
  Unknown database type json requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.
Does not support mysql->json type？

**Comment by Xethron** [comment]
Thank you for reporting this. It should be fixed in v2.0.0

**Comment by Broutard** [comment]
Json fields still generated as : $table->text('data') instead of $table->json('data')
